/*
 * This file is generated by jOOQ.
 */
package top.wuhunyu.jooq.transaction.codegen.tables.daos;


import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import top.wuhunyu.jooq.transaction.codegen.tables.TUser;
import top.wuhunyu.jooq.transaction.codegen.tables.records.TUserRecord;


/**
 * 用户信息
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class TUserDao extends DAOImpl<TUserRecord, top.wuhunyu.jooq.transaction.codegen.tables.pojos.TUser, Long> {

    /**
     * Create a new TUserDao without any configuration
     */
    public TUserDao() {
        super(TUser.T_USER, top.wuhunyu.jooq.transaction.codegen.tables.pojos.TUser.class);
    }

    /**
     * Create a new TUserDao with an attached configuration
     */
    @Autowired
    public TUserDao(Configuration configuration) {
        super(TUser.T_USER, top.wuhunyu.jooq.transaction.codegen.tables.pojos.TUser.class, configuration);
    }

    @Override
    public Long getId(top.wuhunyu.jooq.transaction.codegen.tables.pojos.TUser object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.wuhunyu.jooq.transaction.codegen.tables.pojos.TUser> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(TUser.T_USER.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<top.wuhunyu.jooq.transaction.codegen.tables.pojos.TUser> fetchById(Long... values) {
        return fetch(TUser.T_USER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public top.wuhunyu.jooq.transaction.codegen.tables.pojos.TUser fetchOneById(Long value) {
        return fetchOne(TUser.T_USER.ID, value);
    }

    /**
     * Fetch records that have <code>user_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<top.wuhunyu.jooq.transaction.codegen.tables.pojos.TUser> fetchRangeOfUserName(String lowerInclusive, String upperInclusive) {
        return fetchRange(TUser.T_USER.USER_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_name IN (values)</code>
     */
    public List<top.wuhunyu.jooq.transaction.codegen.tables.pojos.TUser> fetchByUserName(String... values) {
        return fetch(TUser.T_USER.USER_NAME, values);
    }
}
