/*
 * This file is generated by jOOQ.
 */
package top.wuhunyu.jooq.transaction.codegen;


import top.wuhunyu.jooq.transaction.codegen.tables.TUser;


/**
 * Convenience access to all tables in test.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 用户信息
     */
    public static final TUser T_USER = TUser.T_USER;
}
