/*
 * This file is generated by jOOQ.
 */
package top.wuhunyu.jooq.transaction.codegen.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import top.wuhunyu.jooq.transaction.codegen.Keys;
import top.wuhunyu.jooq.transaction.codegen.Test;
import top.wuhunyu.jooq.transaction.codegen.tables.records.TUserRecord;


/**
 * 用户信息
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUser extends TableImpl<TUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>test.t_user</code>
     */
    public static final TUser T_USER = new TUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TUserRecord> getRecordType() {
        return TUserRecord.class;
    }

    /**
     * The column <code>test.t_user.id</code>. 主键
     */
    public final TableField<TUserRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "主键");

    /**
     * The column <code>test.t_user.user_name</code>. 用户名称
     */
    public final TableField<TUserRecord, String> USER_NAME = createField(DSL.name("user_name"), SQLDataType.VARCHAR(120).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "用户名称");

    private TUser(Name alias, Table<TUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private TUser(Name alias, Table<TUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("用户信息"), TableOptions.table());
    }

    /**
     * Create an aliased <code>test.t_user</code> table reference
     */
    public TUser(String alias) {
        this(DSL.name(alias), T_USER);
    }

    /**
     * Create an aliased <code>test.t_user</code> table reference
     */
    public TUser(Name alias) {
        this(alias, T_USER);
    }

    /**
     * Create a <code>test.t_user</code> table reference
     */
    public TUser() {
        this(DSL.name("t_user"), null);
    }

    public <O extends Record> TUser(Table<O> child, ForeignKey<O, TUserRecord> key) {
        super(child, key, T_USER);
    }

    @Override
    public Schema getSchema() {
        return Test.TEST;
    }

    @Override
    public UniqueKey<TUserRecord> getPrimaryKey() {
        return Keys.KEY_T_USER_PRIMARY;
    }

    @Override
    public List<UniqueKey<TUserRecord>> getKeys() {
        return Arrays.<UniqueKey<TUserRecord>>asList(Keys.KEY_T_USER_PRIMARY);
    }

    @Override
    public TUser as(String alias) {
        return new TUser(DSL.name(alias), this);
    }

    @Override
    public TUser as(Name alias) {
        return new TUser(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TUser rename(String name) {
        return new TUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TUser rename(Name name) {
        return new TUser(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
