/*
 * This file is generated by jOOQ.
 */
package top.wuhunyu.jooq.transaction.codegen.tables.interfaces;


import java.io.Serializable;


/**
 * 用户信息
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITUser extends Serializable {

    /**
     * Setter for <code>test.t_user.id</code>. 主键
     */
    public void setId(Long value);

    /**
     * Getter for <code>test.t_user.id</code>. 主键
     */
    public Long getId();

    /**
     * Setter for <code>test.t_user.user_name</code>. 用户名称
     */
    public void setUserName(String value);

    /**
     * Getter for <code>test.t_user.user_name</code>. 用户名称
     */
    public String getUserName();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITUser
     */
    public void from(ITUser from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITUser
     */
    public <E extends ITUser> E into(E into);
}
